version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  backend:
    build:
      context: ../backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: ../.env
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
  ai:
    build:
      context: ../ai
    command: uvicorn service:app --host 0.0.0.0 --port 8001 --reload
    env_file: ../.env
    depends_on:
      - backend
    ports:
      - '8001:8001'
  web:
    build:
      context: ../web
    command: npm run dev
    env_file: ../.env
    depends_on:
      - backend
    ports:
      - '3000:3000'
  mobile:
    build:
      context: ../mobile
    command: npm start
    env_file: ../.env
    depends_on:
      - backend
    ports:
      - '19006:19006'
volumes:
  postgres_data:
