[project]
name = "appfit-ai"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "pydantic>=2",
  "openai",
]

[project.optional-dependencies]
dev = ["pytest", "ruff", "black"]
